pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub'                 
        DOCKERHUB_USERNAME    = 'sayurupriyanjana'             
        IMAGE_TAG             = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
        
        // AWS Credentials binding for Terraform
        AWS_CREDS = credentials('aws-credentials') // Ensure you have this ID in Jenkins
        AWS_ACCESS_KEY_ID     = "${AWS_CREDS_USR}"
        AWS_SECRET_ACCESS_KEY = "${AWS_CREDS_PSW}"
        AWS_REGION            = "ap-south-1"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build and Tag Images') {
            steps {
                script {
                    echo "Building Backend..."
                    sh "docker build -t ${DOCKERHUB_USERNAME}/mafia-backend:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/mafia-backend:latest ./backend"
                    
                    echo "Building Frontend..."
                    sh "docker build -t ${DOCKERHUB_USERNAME}/mafia-frontend:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/mafia-frontend:latest ./frontend"
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS) {
                        sh """
                        docker push ${DOCKERHUB_USERNAME}/mafia-backend:${IMAGE_TAG}
                        docker push ${DOCKERHUB_USERNAME}/mafia-backend:latest
                        docker push ${DOCKERHUB_USERNAME}/mafia-frontend:${IMAGE_TAG}
                        docker push ${DOCKERHUB_USERNAME}/mafia-frontend:latest
                        """
                    }
                }
            }
        }

        stage('Provision Infrastructure (Terraform)') {
            steps {
                script {
                    // Initialize and Apply Terraform
                    sh "terraform init"
                    sh "terraform apply -auto-approve"
                    
                    // Capture the Dynamic IP from Terraform Output
                    env.EC2_IP = sh(script: "terraform output -raw ec2_public_ip", returnStdout: true).trim()
                    echo "Infrastructure Provisioned. Deploying to: ${env.EC2_IP}"
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    // We use the key generated by Terraform in the workspace (mafia-key.pem)
                    // Ensure correct permissions on the key file
                    sh "chmod 400 mafia-key.pem"
                    
                    // 1. Copy the deployment compose file to the server
                    // Note: We use -i mafia-key.pem instead of sshagent
                    sh "scp -i mafia-key.pem -o StrictHostKeyChecking=no docker-compose.deploy.yml ubuntu@${env.EC2_IP}:/home/ubuntu/docker-compose.yml"
                    
                    // 2. SSH in and restart containers
                    def remoteCommand = """
                        cd /home/ubuntu
                        
                        # Create .env for Docker tags
                        echo "IMAGE_TAG=${IMAGE_TAG}" > .env
                        
                        # Pull and Up
                        sudo docker compose pull
                        sudo docker compose up -d
                    """
                    
                    sh "ssh -i mafia-key.pem -o StrictHostKeyChecking=no ubuntu@${env.EC2_IP} '${remoteCommand}'"
                }
            }
        }
    }

    post {
        success {
            echo "Deployment Successful! App is running at http://${env.EC2_IP}:5173"
        }
        failure {
            echo "Pipeline failed."
        }
    }
}